---
galaxy_info:
  author: Alex Lapinski
  description: Ansible Role to install pi-hole on a raspberry pi (https://pi-hole.net/)
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - raspbian
  galaxy_tags: []

dependencies: []
