---
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  handlers:
    - name: apt-update
      apt: update-cache=yes
  roles:
    - baseupdates
    - motioneye
    - dns
    - name: reverse_proxy
      vars:
        site_domain: cam.local.net
        target_port: 8765
    - name: reverse_proxy
      vars:
        site_domain: hab.local.net
        target_port: 8080
    - name: openhab