---
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  handlers:
    - name: apt-update
      apt: update-cache=yes
  roles:
    - name: raspbian.datadog
      vars:
        datadog_api_key: ***REMOVED***
    # - name: alexlapinski.ansible_role_raspbian_baseline
    # - name: alexlapinski.ansible_role_raspbian_motioneye
    # - name: alexlapinski.ansible_role_raspbian_dnsmasq
    #  vars:
    #    localdomain: local.net
    #    upstream_dns_servers:
    #      - 8.8.8.8
    #      - 8.8.4.4
    #    dnsentries:
    #      - domain: cam.local.net
    #        ip: 192.168.1.112
    #      - domain: hab.local.net
    #        ip: 192.168.1.112
    #- name: alexlapinski.ansible_role_raspbian_reverse_proxy
    #  vars:
    #    site_domain: cam.local.net
    #    target_port: 8765
    #- name: alexlapinski.ansible_role_raspbian_reverse_proxy
    #  vars:
    #    site_domain: hab.local.net
    #    target_port: 8080
    #- name: alexlapinski.ansible_role_raspbian_openhab
    # - name: alexlapinski.ansible_role_raspbian_pi-hole


    # TODO: Enable New DNS Entries --- GUI App Based?