---
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  handlers:
    - name: apt-update
      apt: update-cache=yes
  roles:
    - name: baseupdates
    - name: motioneye
    - name: dns
      vars:
        localdomain: local.net
        upstream_dns_servers:
          - 8.8.8.8
          - 8.8.4.4
        dnsentries:
          - domain: cam.local.net
            ip: 192.168.1.112
          - domain: hab.local.net
            ip: 192.168.1.112
    - name: reverse_proxy
      vars:
        site_domain: cam.local.net
        target_port: 8765
    - name: reverse_proxy
      vars:
        site_domain: hab.local.net
        target_port: 8080
    - name: openhab
    # - name: pi-hole