#- name:
  #apt:
    # sudo git clone https://github.com/openhab/openhabian.git /opt/openhabian
    # sudo ln -s /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config# execute
    # sudo openhabian-config