# ref: https://certbot.eff.org/lets-encrypt/debianstretch-nginx
---
- name: Install certbot
  apt:
    name: certbot
    state: present

- name: Install certbot (python)
  apt:
    name: python-certbot-nginx
    state: present

- name: Setup Nginx with SSL
  become: yes
  shell: certbot --nginx

- name: Restart Nginx
  service:
    name: nginx
    state: restarted