---
- name: Install DNSMasq
  apt:
    name: dnsmasq

- name: Record DNSMasq Installed
  set_fact:
    cacheable: yes
    key_value: dnsmasq_installed=yes


- name: Remove Old DNSMasq Config
  file:
    name: /etc/dnsmasq.conf
    state: absent

- name: Provision DNSMasq Config
  template:
    src: templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Update Hosts file
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: Start / Init Dnsmasq Daemon
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes
    daemon_reload: yes
