---
- name: install Debian apt key
  apt_key: 
    url: 'https://ftp-master.debian.org/keys/archive-key-9.asc'
    id: 'E1CF20DDFFE4B89E802658F1E0B11894F66AEC98'
    state: present
  notify: apt-update
- name: install Debian apt repositories
  apt_repository: 
    repo: 'deb http://ftp.debian.org/debian {{item}} main contrib non-free'
    state: present
  with_items:
    - stable
    - testing
    - unstable
    - experimental
  notify: apt-update