# 
# @meta name: RaspberryPi - Base Updates
# @meta author: Alex Lapinski
# @meta email: contact@alexlapinski.name
# @meta description: Base updates (apt update & apt repo), as well as setting the timezone
# @meta license: MIT
#
#
---
galaxy_info:
  author: Alex Lapinski
  description: Base OS Updates (update apt, upgrade, etc.)
  license: MIT
  min_ansible_version: 1.2
  galaxy_tags: []
  platforms:
    - name: raspbian
      version:
        - all

dependencies: []
