---
- name: Create site configuration
  template:
    src: templates/reverse_proxy_site.conf.j2
    dest: /etc/nginx/sites-available/{{ site_domain }}.conf

- name: Create Symlink (Enable Site)
  file:
    src: /etc/nginx/sites-available/{{ site_domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ site_domain }}
    state: link

- name: Restart Nginx
  service:
    name: nginx
    state: restarted