- name: Install Dependencies
  apt:
    name: sysstat
    update_cache: true
    state: present

- name: Download Bash Script
  get_url:
    url: https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh
    dest: /tmp/datadog-installer.sh
    mode: 0777

- name: Execute Bash Script
  shell: /tmp/datadog-installer.sh
  environment:
    DD_API_KEY: "{{datadog_api_key}}"

- name: Remove the Bash Script
  file:
    path: /tmp/datadog-installer.sh
    state: absent